name: basedocker

on: 
  push:
    branches: 
      - master

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build base image
      run: docker build ./basedocker/ --file ./basedocker/Dockerfile --tag tarscloud/tars-base:latest
    - name: docker push
      run: docker login -u ${{ secrets.name }} -p ${{ secrets.pass }} && docker push tarscloud/tars-base:latest
