name: basedocker-full

on:
  push:
    branches:
      - master
    paths:
      - "basedocker/full/*"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Build base image
        run: docker build ./basedocker/ --file ./basedocker/full/Dockerfile --tag tarscloud/tars-env-full:latest
      - name: docker push
        run: docker login -u ${{ secrets.name }} -p ${{ secrets.pass }} && docker push tarscloud/tars-env-full:latest
