name: framework

on:
  push:
    branches:
      - master
    paths:
      - "./framework/**"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Build framework image
        run: docker build ./framework/ --file ./framework/Dockerfile --tag tarscloud/framework:latest
