name: tars

on: [push]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build tars image
      run: docker build ./framework/ --file ./framework/Dockerfile --tag framework:$(date +%s)
