name: tars-dev

on:
  push:
    branches:
      - dev
    paths:
      - "tars/**"
  pull_request:
    branches:
      - dev
    paths:
      - "tars/**"
  schedule:
    - cron: 0 23 * * *
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Build tars-dev image
        run: docker build ./tars/ --file ./tars/Dockerfile --tag tars:dev-$(date +%s)
