name: tarsnode

on: 
  push:
    branches: 
      - master
      
jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build tarsnode image
      run: docker build ./tarsnode/ --file ./tarsnode/Dockerfile --tag tarscloude/tars-node:latest
    - name: docker push
      run: docker login -u ${{ secrets.name }} -p ${{ secrets.pass }} && docker push tarscloud/tars-node:latest
