name: tars

on: 
  push:
    branches: 
      - master
      
jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build tars image
      run: docker build ./tars/ --file ./tars/Dockerfile --tag tarscloude/tars:latest
    - name: docker push
      run: docker login -u ${{ secrets.name }} -p ${{ secrets.pass }} && docker push tarscloud/tars:latest
