name: tars

on: 
  push:
    branches: 
      - master
  schedule:
    - cron: '0 23 * * *'      
jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build tars image
      run: docker build ./tars/ --file ./tars/Dockerfile --tag tarscloud/tars:latest
