name: tarsnode-full-dev

on:
  push:
    branches:
      - dev
    paths:
      - "tarsnode/full/**"
  pull_request:
    branches:
      - dev
    paths:
      - "tarsnode/full/**"
  schedule:
    - cron: 0 23 * * *
jobs:
  build-full:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Build tarsnode-full-dev image
        run: |
          cp ./tarsnode/entrypoint.sh ./tarsnode/full/entrypoint.sh 
          cd ./tarsnode/full
          docker build . --file Dockerfile --tag tarsnode:full-$(date +%s)
