name: tarsnode

on: 
  push:
    branches: 
      - master
  schedule:
    - cron: '0 23 * * *'      
jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build tarsnode image
      run: docker build ./tarsnode/ --file ./tarsnode/Dockerfile --tag tarscloud/tars-node:latest
