name: tarsnode-full

on:
  push:
    branches:
      - master
    paths:
      - "tarsnode/full/**"
  pull_request:
    branches:
      - master
    paths:
      - "tarsnode/full/**"
jobs:
  build-full:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Build tarsnode latest full image
        run: |
          cp ./tarsnode/entrypoint.sh ./tarsnode/full/entrypoint.sh
          cd ./tarsnode/full 
          docker build . --file Dockerfile --tag tarscloud/tars-node:latest
